-- Rename the old 'image' column to 'image_url' (if it exists)
ALTER TABLE interior_packages RENAME COLUMN image TO image_url;

-- Add the missing new columns to your existing table
ALTER TABLE interior_packages 
ADD COLUMN IF NOT EXISTS price_suffix TEXT DEFAULT '/sq.ft (Frame & Shutter)',
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- Create the required sections table (Using UUID for the package_id to match your existing table)
CREATE TABLE IF NOT EXISTS interior_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id UUID REFERENCES interior_packages(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the items table
CREATE TABLE IF NOT EXISTS interior_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT REFERENCES interior_sections(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and insert permissions for the new tables
ALTER TABLE interior_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE interior_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all actions" ON interior_sections FOR ALL USING (true);
CREATE POLICY "Allow all actions" ON interior_items FOR ALL USING (true);
