-- Run this on Supabase SQL Editor

-- Table: interior_packages
CREATE TABLE interior_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    price_suffix TEXT DEFAULT '/sq.ft (Frame & Shutter)',
    image_url TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: interior_sections
CREATE TABLE interior_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES interior_packages(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: interior_items
CREATE TABLE interior_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT REFERENCES interior_sections(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE interior_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE interior_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE interior_items ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public Read Access" ON interior_packages FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON interior_sections FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON interior_items FOR SELECT USING (true);

-- Admin read/write permissions (For simplicity, allowing authenticated/anon based on your setup setup)
CREATE POLICY "Allow all actions" ON interior_packages FOR ALL USING (true);
CREATE POLICY "Allow all actions" ON interior_sections FOR ALL USING (true);
CREATE POLICY "Allow all actions" ON interior_items FOR ALL USING (true);
