-- Run this in the Supabase SQL Editor to update your existing table
-- It looks like you already had an older 'interior_packages' table!

-- Add the missing columns to the existing table
ALTER TABLE interior_packages 
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS price_suffix TEXT DEFAULT '/sq.ft (Frame & Shutter)',
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- If you get an error that 'image_url' already exists but you had 'image' before, you can rename it instead:
-- ALTER TABLE interior_packages RENAME COLUMN image TO image_url;

-- Ensure the required nested tables exist
CREATE TABLE IF NOT EXISTS interior_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES interior_packages(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS interior_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT REFERENCES interior_sections(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE interior_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE interior_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE interior_items ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated admin users
CREATE POLICY "Allow all actions" ON interior_packages FOR ALL USING (true);
CREATE POLICY "Allow all actions" ON interior_sections FOR ALL USING (true);
CREATE POLICY "Allow all actions" ON interior_items FOR ALL USING (true);
